// Package graph turns a raw scroll capture into a content graph: text runs
// reassembled, chrome separated from content, hidden content quarantined,
// heading levels inferred from typography rather than tag names, and reading
// order recomputed from geometry.
//
// Everything downstream -- Markdown, HTML, JSON, the MCP tool surface, the
// benchmark -- renders from this one structure, so the formats cannot drift
// apart.
package graph

import "time"

// Source records where a piece of content came from. Consumers must be able to
// tell text that was really in the document from text a model inferred by
// looking at pixels, and that distinction has to survive every format change.
type Source string

const (
	// SourceDOM is text that existed in the rendered document. It is exact.
	SourceDOM Source = "dom"
	// SourceStatic is text recovered from the served HTML without a browser.
	SourceStatic Source = "static"
	// SourceCanvasFallback is a canvas element's own accessibility fallback
	// content, authored by the site. Exact, and the cheapest recovery there is.
	SourceCanvasFallback Source = "canvas_fallback"
	// SourceCanvasScene is text recovered from a 3D scene graph: node names,
	// mesh names, embedded metadata. Exact when it works.
	SourceCanvasScene Source = "canvas_scene"
	// SourceCanvasOCR is text read off rasterised pixels by optical character
	// recognition. Deterministic, and it fails loudly rather than quietly.
	SourceCanvasOCR Source = "canvas_ocr"
	// SourceCanvasVision is a description generated by a vision model from
	// rasterised pixels. Plausible, not authoritative.
	SourceCanvasVision Source = "canvas_vision"
)

// Verification records whether a recovered string was confirmed against the
// text the site actually shipped.
//
// This is what converts an open-ended hallucination problem into a bounded
// confidence-scoring one. Most canvas headlines exist somewhere in the payload
// before they become pixels; finding the string there proves the recovery is
// real without ever using the payload as a source of content.
type Verification string

const (
	// VerificationNone means no cross-check applies: the text came from the DOM.
	VerificationNone Verification = ""
	// VerificationConfirmed means the recovered string was found in the text
	// the site shipped.
	VerificationConfirmed Verification = "confirmed"
	// VerificationSpeculative means it was not found. The block is excluded
	// from the default payload.
	VerificationSpeculative Verification = "speculative"
)

// Confidence is reported as a coarse bucket, not a decimal.
//
// A wrong number is worse than no number, because people trust numbers more
// than prose: "0.87" reads as a measurement and invites arithmetic, while
// "medium" reads as a judgement and invites checking. Until there is a
// benchmark corpus large enough to calibrate against, the honest output is a
// bucket. The underlying score is retained for tuning but is not the headline.
type Confidence string

const (
	ConfidenceHigh   Confidence = "high"
	ConfidenceMedium Confidence = "medium"
	ConfidenceLow    Confidence = "low"
)

// Bucket converts an internal score to the reported bucket.
func Bucket(score float64) Confidence {
	switch {
	case score >= 0.85:
		return ConfidenceHigh
	case score >= 0.6:
		return ConfidenceMedium
	default:
		return ConfidenceLow
	}
}

// BlockType is the shape of a block.
type BlockType string

const (
	TypeHeading   BlockType = "heading"
	TypeParagraph BlockType = "paragraph"
	TypeList      BlockType = "list"
	TypeListItem  BlockType = "list_item"
	TypeQuote     BlockType = "quote"
	TypeImage     BlockType = "image"
	TypeMedia     BlockType = "media"
	TypeCode      BlockType = "code"
	TypeTable     BlockType = "table"
	TypeLabel     BlockType = "label"
)

// Region says which part of the page a block belongs to. Chrome is kept rather
// than discarded: "what is the navigation hierarchy" is one of the questions
// the benchmark asks, and a distiller that threw the navigation away could not
// answer it.
type Region string

const (
	RegionMain   Region = "main"
	RegionNav    Region = "nav"
	RegionHeader Region = "header"
	RegionFooter Region = "footer"
	RegionAside  Region = "aside"
	RegionForm   Region = "form"
	RegionDialog Region = "dialog"
)

// IsChrome reports whether a region is page furniture rather than the content
// a reader came for.
func (r Region) IsChrome() bool {
	switch r {
	case RegionNav, RegionHeader, RegionFooter:
		return true
	}
	return false
}

// Block is one addressable unit of content.
type Block struct {
	ID   string    `json:"id"`
	Type BlockType `json:"type"`
	// Level is the heading level, 1 to 6. Zero for non-headings.
	Level int    `json:"level,omitempty"`
	Text  string `json:"text"`
	Order int    `json:"order"`

	Source Source `json:"source"`
	// Confidence is the reported bucket. Score is the underlying number, kept
	// for calibration work and deliberately not the headline.
	Confidence Confidence `json:"confidence"`
	Score      float64    `json:"score,omitempty"`
	// Verified is set only on blocks recovered from pixels.
	Verified Verification `json:"verified,omitempty"`

	Checkpoint int        `json:"checkpoint"`
	BBox       [4]float64 `json:"bbox"`

	Region Region `json:"region"`
	// SectionID is the id of the section this block belongs to, which is what
	// lets an agent pull one section instead of the whole artifact.
	SectionID string `json:"section_id,omitempty"`

	// Href is set when the whole block is a link.
	Href string `json:"href,omitempty"`
	// MediaID links an image or media block to its media entry.
	MediaID string `json:"media_id,omitempty"`
	// ListOrdered distinguishes numbered from bulleted lists.
	ListOrdered bool `json:"list_ordered,omitempty"`

	// Style is the typographic evidence the heading inference used. Kept
	// because a wrong heading level is the most common extraction complaint,
	// and without this there is no way to see why the level was chosen.
	Style StyleInfo `json:"style,omitempty"`

	// Flags records anything unusual the extraction noticed about this run:
	// text hidden by colour, metadata that hit its cap, control characters
	// stripped. A consumer that wants to be suspicious has something to be
	// suspicious about.
	Flags []string `json:"flags,omitempty"`
}

// StyleInfo is the rendered typography of a block.
type StyleInfo struct {
	FontSize   float64 `json:"font_size,omitempty"`
	Weight     int     `json:"weight,omitempty"`
	Tracking   float64 `json:"tracking,omitempty"`
	Uppercase  bool    `json:"uppercase,omitempty"`
	Italic     bool    `json:"italic,omitempty"`
	Family     string  `json:"family,omitempty"`
	MaxOpacity float64 `json:"max_opacity,omitempty"`
}

// LatentBlock is text that exists in the document but was never rendered.
//
// # Read this before touching anything that handles it
//
// This is the quarantine, and it holds the exact material the visibility filter
// exists to exclude. That is deliberate and it is safe only while it stays in
// its own box. A collapsed accordion body is content a reader can reach with a
// click; an off-screen paragraph addressed to whatever AI is reading the page
// is an attack. They are indistinguishable to any walker, so both are kept and
// neither is promoted.
//
// Four structural rules keep the box shut, and every one of them is load-bearing:
//
//  1. Latent content lives under its own top-level key. It is never appended to
//     Blocks, and there is no code path that merges the two.
//  2. It is retrieved by a separate tool, never by a flag on the normal content
//     call. A flag is one typo away from being set by default.
//  3. Every latent block carries its trust marker into every output format, so
//     a reader that receives one always knows what it received.
//  4. It is excluded from the headline token count, or the feature quietly
//     makes the project's own numbers worse for everyone who never uses it.
//
// A test asserts rule 1 on every emitted format. If that test ever fails, the
// security claim this project leads with is gone, not weakened.
type LatentBlock struct {
	ID   string    `json:"id"`
	Type BlockType `json:"type"`
	Text string    `json:"text"`

	// Reason is why this text was never rendered.
	Reason string `json:"reason"`
	// ControlLabel is the accessible name of the widget that would reveal it --
	// the tab, the accordion header, the summary. This is the whole point of
	// keeping the tier: an artifact can say "there is a section behind a tab
	// labelled Pricing" instead of silently omitting it.
	ControlLabel string `json:"control_label,omitempty"`
	ControlKind  string `json:"control_kind,omitempty"`

	Region Region `json:"region,omitempty"`
	Href   string `json:"href,omitempty"`
	Level  int    `json:"level,omitempty"`

	// Trust is the marker that survives into every format. It is a constant,
	// not a computed field, because a computed field can compute to empty.
	Trust string `json:"trust"`

	Flags []string `json:"flags,omitempty"`
}

// LatentTrustMarker is the fixed string every latent block carries.
const LatentTrustMarker = "untrusted-hidden-content"

// Gap is a disclosure control whose content was not opened.
//
// An agent that knows a Specifications tab exists can go and get it another
// way. An agent told nothing assumes the page had no specifications.
type Gap struct {
	Label string `json:"label"`
	Kind  string `json:"kind"`
	// Reason says why it was not opened.
	Reason string `json:"reason"`
	// LatentIDs are the latent blocks this control would reveal, when they are
	// already captured.
	LatentIDs []string `json:"latent_ids,omitempty"`
}

// Section is a run of blocks under one heading. Sections are the unit the MCP
// tools page over, so an agent can read the part it needs without pulling the
// artifact into its context.
type Section struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Level int    `json:"level"`
	// FirstBlock and LastBlock are inclusive block ids bounding the section.
	FirstBlock string `json:"first_block"`
	LastBlock  string `json:"last_block"`
	BlockCount int    `json:"block_count"`
	// Chars is the section's text length, which is what an agent needs to
	// decide whether pulling it will fit in its budget.
	Chars int `json:"chars"`
	// Tokens is an estimate, not a measurement. See the tokens package.
	Tokens int `json:"tokens"`
}

// Action is a link, button or form: the things a visitor can do, which most
// extraction tools omit entirely.
type Action struct {
	ID     string  `json:"id"`
	Type   string  `json:"type"` // link | form | button
	Label  string  `json:"label"`
	Href   string  `json:"href,omitempty"`
	Method string  `json:"method,omitempty"`
	Fields []Field `json:"fields,omitempty"`
	Region Region  `json:"region,omitempty"`
	// Internal marks links that stay on the same registrable domain.
	Internal bool `json:"internal,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
}

// Field is one form control a visitor is expected to fill in.
type Field struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Label    string   `json:"label,omitempty"`
	Required bool     `json:"required,omitempty"`
	Options  []string `json:"options,omitempty"`
	Pattern  string   `json:"pattern,omitempty"`
}

// Media is an image, video or model.
type Media struct {
	ID      string `json:"id"`
	Type    string `json:"type"` // image | video | model
	Src     string `json:"src"`
	Alt     string `json:"alt,omitempty"`
	Caption string `json:"caption,omitempty"`
	// Source says where the description came from: the page's own alt text, a
	// figure caption, or a vision model.
	Source     string     `json:"source"`
	Confidence Confidence `json:"confidence,omitempty"`
	Width      float64    `json:"width,omitempty"`
	Height     float64    `json:"height,omitempty"`
	// Local is the path inside the artifact's media/ folder, when the asset
	// was downloaded.
	Local string `json:"local,omitempty"`
	// Flags records metadata that hit its cap.
	Flags []string `json:"flags,omitempty"`
}

// Link is an outbound reference.
type Link struct {
	Href     string `json:"href"`
	Text     string `json:"text"`
	Internal bool   `json:"internal"`
	Region   Region `json:"region,omitempty"`
}

// Stats is the evidence for the project's central claim.
type Stats struct {
	OriginalBytes  int64 `json:"original_bytes"`
	ArtifactBytes  int64 `json:"artifact_bytes"`
	OriginalTokens int   `json:"original_tokens"`
	// ArtifactTokens counts the default payload only. Latent content is
	// excluded: it is not delivered by default, and counting it would make the
	// headline number worse for every caller who never asks for it.
	ArtifactTokens int `json:"artifact_tokens"`
	// LatentTokens is reported separately so the exclusion is visible rather
	// than convenient.
	LatentTokens int `json:"latent_tokens,omitempty"`

	Checkpoints  int `json:"checkpoints"`
	RawNodes     int `json:"raw_nodes"`
	ContentNodes int `json:"content_blocks"`
	ChromeNodes  int `json:"chrome_blocks"`
	LatentNodes  int `json:"latent_blocks"`
	DroppedNodes int `json:"dropped_nodes"`
}

// Audit is the artifact's account of its own reliability.
//
// An artifact that reports its own uncertainty is a categorically different
// object from one that does not, and no competing extractor ships this.
type Audit struct {
	// GraphRetention is the share of the text the capture observed that
	// survived into the emitted graph.
	//
	// The name is narrow on purpose. It measures the graph stage, not the
	// capture stage: if the sweep missed half the page, this number cheerfully
	// reports that all of the remaining half was retained. That is true and it
	// is not what "coverage" would be read to mean. True coverage against
	// hand-written ground truth is a benchmark number, measured where the right
	// answer is actually known, and it lives in the benchmark report rather
	// than here.
	GraphRetention float64 `json:"graph_retention"`
	// ObservedChars and EmittedChars are the raw terms, so the ratio can be
	// checked rather than trusted.
	ObservedChars int `json:"observed_chars"`
	EmittedChars  int `json:"emitted_chars"`

	// OrderConfidence is how much to trust the reading order.
	OrderConfidence Confidence `json:"order_confidence"`
	OrderScore      float64    `json:"order_score,omitempty"`
	// OrderBasis is how the order was computed: "geometry" when document
	// coordinates were meaningful, "checkpoint" when the page scrolled by
	// transform and coordinates were not.
	OrderBasis string `json:"order_basis"`
	// OrderAgreement is how much the geometric ordering and the
	// first-appearance ordering agree. Both are computed anyway, so comparing
	// them is nearly free, and divergence is exactly where reading order goes
	// wrong.
	OrderAgreement float64 `json:"order_agreement"`

	// HeadingSeparation measures how cleanly the type scale separated into
	// levels. A clean gap between size clusters means the heading inference had
	// something real to work with; an overlapping continuum means it guessed.
	HeadingSeparation float64    `json:"heading_separation"`
	HeadingConfidence Confidence `json:"heading_confidence"`

	// Dropped counts the runs that were captured but did not become blocks,
	// grouped by why.
	//
	// This is the difference between an artifact that is empty and an artifact
	// that explains itself. A page that comes back with nothing is the single
	// most alarming output this tool can produce, and without this the user has
	// no way to tell "the page really is a canvas" from "every run was excluded
	// by a threshold". Both have happened; only one is a bug.
	Dropped []DropCount `json:"dropped,omitempty"`

	// ReachedBottom is false when a budget stopped the sweep early.
	ReachedBottom bool `json:"reached_bottom"`
	// FramesBlocked counts cross-origin iframes whose content could not be read.
	FramesBlocked int `json:"frames_blocked,omitempty"`
	// CanvasesUnrecovered counts canvases that passed the size gate but yielded
	// nothing.
	CanvasesUnrecovered int `json:"canvases_unrecovered,omitempty"`
	// Notes are human-readable limitations discovered during the render.
	Notes []string `json:"notes,omitempty"`
}

// DropCount is one reason runs were excluded, and how many.
//
// It deliberately carries no sample of the excluded text. An earlier version
// did, so that the reason could be checked rather than trusted, and the
// adversarial corpus caught it within one run: the runs being excluded are
// precisely the hidden ones, and quoting one into the audit section handed the
// text straight back to the reader through the diagnostic meant to explain why
// it had been withheld.
//
// Counts and reasons carry the diagnostic value. Anyone who needs to see the
// text itself can replay a snapshot, where it is labelled for what it is.
type DropCount struct {
	Reason string `json:"reason"`
	Runs   int    `json:"runs"`
	Chars  int    `json:"chars"`
}

// Provenance records how this artifact was produced, in enough detail to
// reproduce it.
type Provenance struct {
	// Tier is which rung of the escalation ladder answered: fetch, render,
	// sweep or recover.
	Tier string `json:"tier"`
	// TierReason is the scoring that led to that decision, so a caller can see
	// why a page was judged cheap or expensive rather than having to guess.
	TierReason string `json:"tier_reason,omitempty"`
	// TierScore is the escalation score itself.
	TierScore float64 `json:"tier_score,omitempty"`
	// TierPinned reports that the tier came from a per-domain memory rather
	// than from a fresh judgement. Once a domain escalates it stays escalated,
	// so a page near the threshold does not oscillate between runs.
	TierPinned bool `json:"tier_pinned,omitempty"`

	// Libraries are the animation, scroll and 3D libraries detected.
	Libraries []string `json:"libraries,omitempty"`
	// NormalizerVersion is part of the content hash. Changing normalization
	// invalidates every cached artifact, so it is recorded rather than implied.
	NormalizerVersion int `json:"normalizer_version"`
	// SchemaVersion of the trace payload.
	Trace any `json:"trace,omitempty"`

	// Blocked records that the site refused this client.
	Blocked       bool   `json:"blocked,omitempty"`
	BlockedReason string `json:"blocked_reason,omitempty"`

	// Private marks an artifact produced against an authenticated or
	// user-profile session. It is never eligible for a shared cache and never
	// included in a diagnostic bundle.
	Private bool `json:"private,omitempty"`

	// Incomplete marks a partial artifact from progressive emission. It is
	// checked at the cache boundary: a partial result must never be stored as
	// if it were final.
	Incomplete bool `json:"incomplete,omitempty"`

	// CorpusBytes and CorpusSaturated describe the confirm-only index used for
	// canvas cross-checking. A saturated index makes a negative result weaker
	// evidence, and saying so is more useful than pretending otherwise.
	CorpusBytes     int  `json:"corpus_bytes,omitempty"`
	CorpusSaturated bool `json:"corpus_saturated,omitempty"`
}

// Graph is the whole artifact.
type Graph struct {
	SchemaVersion string    `json:"schema_version"`
	URL           string    `json:"url"`
	FinalURL      string    `json:"final_url,omitempty"`
	DistilledAt   time.Time `json:"distilled_at"`
	// ContentHash covers the normalised semantic graph -- block text, type,
	// level, order -- and not the serialised output. Trivial variation in
	// whitespace or asset URLs then does not churn the hash, and re-distilling
	// an unchanged site is genuinely a no-op.
	ContentHash string `json:"content_hash"`
	Generator   string `json:"generator"`

	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	Summary     string `json:"summary"`
	Lang        string `json:"lang,omitempty"`

	Sections []Section `json:"sections"`
	Blocks   []Block   `json:"blocks"`
	Actions  []Action  `json:"actions"`
	MediaAll []Media   `json:"media"`
	Links    []Link    `json:"links"`

	// Structured holds whitelisted facts lifted from JSON-LD. Never raw.
	Structured []StructuredFact `json:"structured,omitempty"`
	// FAQ holds question-and-answer pairs published as FAQPage structured data.
	//
	// They are kept apart from Blocks because their provenance is different:
	// nobody saw these words rendered, they were declared. A consumer that
	// wants only what a visitor could read can ignore this array; one answering
	// a question about the site would be foolish to.
	FAQ []QAPair `json:"faq,omitempty"`

	// Latent is the quarantine. It is a separate top-level key by design and
	// must never be merged into Blocks. See LatentBlock.
	Latent []LatentBlock `json:"latent,omitempty"`
	// Gaps are disclosure controls whose content was not opened.
	Gaps []Gap `json:"gaps,omitempty"`

	Stats      Stats      `json:"stats"`
	Audit      Audit      `json:"audit"`
	Provenance Provenance `json:"provenance"`
}

// ContentBlocks returns only the blocks that are part of the page's content,
// in reading order. Latent content is structurally unreachable from here.
func (g *Graph) ContentBlocks() []Block {
	out := make([]Block, 0, len(g.Blocks))
	for _, b := range g.Blocks {
		if !b.Region.IsChrome() {
			out = append(out, b)
		}
	}
	return out
}

// BlockByID looks up a block.
func (g *Graph) BlockByID(id string) (*Block, bool) {
	for i := range g.Blocks {
		if g.Blocks[i].ID == id {
			return &g.Blocks[i], true
		}
	}
	return nil, false
}

// SectionByID looks up a section.
func (g *Graph) SectionByID(id string) (*Section, bool) {
	for i := range g.Sections {
		if g.Sections[i].ID == id {
			return &g.Sections[i], true
		}
	}
	return nil, false
}

// SectionBlocks returns the blocks belonging to a section, in order.
func (g *Graph) SectionBlocks(id string) []Block {
	var out []Block
	for _, b := range g.Blocks {
		if b.SectionID == id {
			out = append(out, b)
		}
	}
	return out
}
